### ISSUE TITLE
problems when importing the API

### ISSUE THREAD

**Issue by DrChenziyan** [jcreinhold/intensity-normalization#61]
## 🐛 Bug
Hi,
When I import the intensity_normalization API in python(3.9.10), some errors happened and I don't know how to fix them, could you please help me to solve the problem.

```python
from intensity_normalization.normalize.fcm import FCMNormalize
```
Errors:
```
Traceback (most recent call last):
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-d1af5b2a98e3>", line 1, in <cell line: 1>
    from intensity_normalization.normalize.fcm import FCMNormalize
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/intensity_normalization-2.2.3-py3.9.egg/intensity_normalization/normalize/fcm.py", line 18, in <module>
    import pymedio.image as mioi
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/pymedio-0.2.13-py3.9.egg/pymedio/image.py", line 26, in <module>
    import pymedio.base as miob
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/pymedio-0.2.13-py3.9.egg/pymedio/base.py", line 17, in <module>
    import pymedio.typing as miot
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/pymedio-0.2.13-py3.9.egg/pymedio/typing.py", line 29, in <module>
    Float = typing.Union[np.floating[T], builtins.float]
TypeError: 'type' object is not subscriptable
```
Also, this error happened when i
```python
from intensity_normalization.typing import Modality, TissueType
```
```
Traceback (most recent call last):
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-7e9599dbea2b>", line 1, in <cell line: 1>
    from intensity_normalization.typing import Modality, TissueType
  File "/export/bioinfo-team/home/chenzy/anaconda3/envs/d2l/lib/python3.9/site-packages/intensity_normalization-2.2.3-py3.9.egg/intensity_normalization/typing.py", line 435, in <module>
    Float = typing.Union[np.floating[NBit], builtins.float]
TypeError: 'type' object is not subscriptable
```

## Environment

 - intensity-normalization version (e.g., 0.3.8): 2.2.3
 - numpy version (e.g., 1.0):1.21.5
 - OS (e.g., Linux): Linux
 - How you installed intensity-normalization (`conda`, `pip`, source): from source
 - Build command you used (if installed from source): python setup.py install
 - Python version: 3.9.10
 - Any other relevant information:

**Comment by jcreinhold** [comment]
I believe this is a numpy version; numpy v1.22 is required. Re-open if that doesn't fix the issue.
